call DropTables();

DROP PROCEDURE IF EXISTS yelp.DropTables;
DELIMITER //
CREATE PROCEDURE yelp.`DropTables`()
BEGIN

#FAVOURITES
DROP TABLE IF EXISTS FAVOURITES;

#COMPLIMENTED USER DETAILS
DROP TABLE IF EXISTS COMPLIMENTED_USER_DETAILS; 

#COMPLIMENT
DROP TABLE IF EXISTS COMPLIMENT;

#FRIENDSHIP
DROP TABLE IF EXISTS FRIENDSHIP;

#RESTAURANT
DROP TABLE IF EXISTS RESTAURANT;

#SHOPPING
DROP TABLE IF EXISTS SHOPPING;

#HOTEL_TRAVEL
DROP TABLE IF EXISTS HOTEL_TRAVEL;

#RATE
DROP TABLE IF EXISTS RATE;

#REVIEW
DROP TABLE IF EXISTS REVIEW;

#PICTURE
DROP TABLE IF EXISTS PICTURE;

#PROMOTION
DROP TABLE IF EXISTS PROMOTION;

#CHECKIN
DROP TABLE IF EXISTS CHECKIN;

#CATEGORIES
DROP TABLE IF EXISTS CATEGORIES;

#UNREGISTERED_USER
DROP TABLE IF EXISTS UNREGISTERED_USER;

#REGISTERED_USER
DROP TABLE IF EXISTS REGISTERED_USER;

#ADMIN
DROP TABLE IF EXISTS ADMIN;

#USER
DROP TABLE IF EXISTS USER;


END; //
DELIMITER ;