call InsertData();

DROP PROCEDURE IF EXISTS yelp.InsertData;
DELIMITER //
CREATE PROCEDURE yelp.`InsertData`()
BEGIN

DECLARE EXIT handler for sqlexception
BEGIN
	ROLLBACK;
END;

DECLARE EXIT handler for sqlwarning
BEGIN
	ROLLBACK;
END;


START TRANSACTION;

	#USER
	INSERT INTO USER VALUES(null, "ADMIN");
	INSERT INTO USER VALUES(null, "UNREGISTERED_USER");
	INSERT INTO USER VALUES(null, "REGISTERED_USER");
	INSERT INTO USER VALUES(null, "ADMIN");
	INSERT INTO USER VALUES(null, "REGISTERED_USER");
	INSERT INTO USER VALUES(null, "ADMIN");
	INSERT INTO USER VALUES(null, "REGISTERED_USER");
	INSERT INTO USER VALUES(null, "ADMIN");
	INSERT INTO USER VALUES(null, "REGISTERED_USER");
	INSERT INTO USER VALUES(null, "UNREGISTERED_USER");

	#UNREGISTERED_USER
	INSERT INTO UNREGISTERED_USER VALUES(2,"Browsing");
	INSERT INTO UNREGISTERED_USER VALUES(10,"Browsing");

	#REGISTERED_USER
	INSERT INTO REGISTERED_USER VALUES(3,"user_1","user_1","First User", "firstUser@gmail.com","San Jose");
	INSERT INTO REGISTERED_USER VALUES(5,"user_2","user_2","Second User", "secondUser@gmail.com","San Jose");
	INSERT INTO REGISTERED_USER VALUES(7,"user_3","user_3","Third User", "thirdUser@gmail.com","San Jose");
	INSERT INTO REGISTERED_USER VALUES(9,"user_4","user_4","Fourth User", "fourthUser@gmail.com","San Jose");

	#ADMIN
	INSERT into ADMIN VALUES(1, "Ravi","Ravi","RaviKishore","ravi@gmail.com");
	INSERT into ADMIN VALUES(4, "Naveen","Naveen","Naveen","naveen@gmail.com");
	INSERT into ADMIN VALUES(6, "Raghav","Raghav","Raghavendra","raghav@gmail.com");
	INSERT into ADMIN VALUES(8, "Jaspal","Japal","Japal","Jaspal@gmail.com");

	#CATEGORIES
	INSERT INTO CATEGORIES VALUES(null,"Pizza","RESTAURANT","San Jose", "4086543210");
	INSERT INTO CATEGORIES VALUES(null,"Great Mall","SHOPPING","Mountain View", "4087562910");
	INSERT INTO CATEGORIES VALUES(null,"Luxury Stay","HOTEL_TRAVEL","Santa Clara", "8976543210");
	INSERT INTO CATEGORIES VALUES(null,"Punjab Cafe","RESTAURANT","San Jose", "4666543210");
	INSERT INTO CATEGORIES VALUES(null,"Valley Fair Mall","SHOPPING","Santa Clara", "5006543210");
	INSERT INTO CATEGORIES VALUES(null,"Motel","HOTEL_TRAVEL","San Jose", "4566543210");
	INSERT INTO CATEGORIES VALUES(null,"Burritos","RESTAURANT","San Francisco", "4446543210");
	INSERT INTO CATEGORIES VALUES(null,"Shopping Complex","SHOPPING","San Deigo", "6786543210");
	INSERT INTO CATEGORIES VALUES(null,"Vistors","HOTEL_TRAVEL","San Jose", "6546543210");

	#RESTAURANT
	INSERT INTO RESTAURANT VALUES(1,"Italian");
	INSERT INTO RESTAURANT VALUES(4,"Indian");
	INSERT INTO RESTAURANT VALUES(7,"Mexican");

	#SHOPPING
	INSERT INTO SHOPPING VALUES(2,"11 AM - 11 PM");
	INSERT INTO SHOPPING VALUES(5,"10 AM - 10 PM");
	INSERT INTO SHOPPING VALUES(8,"12 AM - 2 PM");

	#HOTEL_TRAVEL
	INSERT INTO HOTEL_TRAVEL VALUES(3,4);
	INSERT INTO HOTEL_TRAVEL VALUES(6,3);
	INSERT INTO HOTEL_TRAVEL VALUES(9,5);

	#FAVOURITES
	INSERT INTO FAVOURITES VALUES (3,1);
	INSERT INTO FAVOURITES VALUES (3,2);
	INSERT INTO FAVOURITES VALUES (3,3);
	INSERT INTO FAVOURITES VALUES (3,6);
	INSERT INTO FAVOURITES VALUES (5,1);
	INSERT INTO FAVOURITES VALUES (5,7);
	INSERT INTO FAVOURITES VALUES (5,4);
	INSERT INTO FAVOURITES VALUES (5,9);
	INSERT INTO FAVOURITES VALUES (7,6);
	INSERT INTO FAVOURITES VALUES (7,4);
	INSERT INTO FAVOURITES VALUES (7,8);
	INSERT INTO FAVOURITES VALUES (7,9);
	INSERT INTO FAVOURITES VALUES (9,5);
	INSERT INTO FAVOURITES VALUES (9,9);
	INSERT INTO FAVOURITES VALUES (9,1);
	INSERT INTO FAVOURITES VALUES (9,4);
	 
	#COMPLIMENT
	INSERT INTO COMPLIMENT VALUES (3,5,"Good");
	INSERT INTO COMPLIMENT VALUES (3,7,"Hi");
	INSERT INTO COMPLIMENT VALUES (5,3,"Thank you");
	INSERT INTO COMPLIMENT VALUES (7,5,"Excellent");
	INSERT INTO COMPLIMENT VALUES (3,9,"Great");
	INSERT INTO COMPLIMENT VALUES (9,5,"How are you");
	INSERT INTO COMPLIMENT VALUES (9,3,"Awesome");
	INSERT INTO COMPLIMENT VALUES (7,3,"Bad");
	INSERT INTO COMPLIMENT VALUES (7,9,"Horrible");
	INSERT INTO COMPLIMENT VALUES (5,7,"Nice");
	INSERT INTO COMPLIMENT VALUES (5,9,"Wow");


	#COMPLIMENTED_USER_DETAILS
	INSERT INTO COMPLIMENTED_USER_DETAILS VALUES(3,"PUBLIC");
	INSERT INTO COMPLIMENTED_USER_DETAILS VALUES(5,"PRIVATE");
	INSERT INTO COMPLIMENTED_USER_DETAILS VALUES(7,"PUBLIC");
	INSERT INTO COMPLIMENTED_USER_DETAILS VALUES(9,"PUBLIC");


	#FRIENDSHIP
	INSERT INTO FRIENDSHIP VALUES(3,5);
	INSERT INTO FRIENDSHIP VALUES(3,7);
	INSERT INTO FRIENDSHIP VALUES(3,9);
	INSERT INTO FRIENDSHIP VALUES(5,7);
	INSERT INTO FRIENDSHIP VALUES(5,9);
	INSERT INTO FRIENDSHIP VALUES(9,5);
	INSERT INTO FRIENDSHIP VALUES(9,7);
	INSERT INTO FRIENDSHIP VALUES(9,3);

	#REVIEW
	INSERT INTO REVIEW VALUES(null, "Awesome place");
	INSERT INTO REVIEW VALUES(null, "Shopping!");
	INSERT INTO REVIEW VALUES(null, "Stay!");
	INSERT INTO REVIEW VALUES(null, "Good place!");
	INSERT INTO REVIEW VALUES(null, "Costly!");
	INSERT INTO REVIEW VALUES(null, "Reasonable");
	INSERT INTO REVIEW VALUES(null, "You must go here!");
	INSERT INTO REVIEW VALUES(null, "Not exactly the best");
	INSERT INTO REVIEW VALUES(null, "Bad");
	INSERT INTO REVIEW VALUES(null, "Horrible");
	INSERT INTO REVIEW VALUES(null, "Great place");
	INSERT INTO REVIEW VALUES(null, "I will visit again!");
	INSERT INTO REVIEW VALUES(null, "Amazing food");
	INSERT INTO REVIEW VALUES(null, "I go here every weekend");
	INSERT INTO REVIEW VALUES(null, "Great service");

	#RATE
	INSERT INTO RATE VALUES(null, 5, 1, "2014/11/30", 3 , 1);
	INSERT INTO RATE VALUES(null, 4, 2, "2014/10/20", 3 , 5);
	INSERT INTO RATE VALUES(null, 4, 3, "2014/09/11", 3 , 9);
	INSERT INTO RATE VALUES(null, 3, 4, "2014/07/22", 3 , 2);
	INSERT INTO RATE VALUES(null, 2, 5, "2014/06/12", 5 , 5);
	INSERT INTO RATE VALUES(null, 4, 6, "2014/05/13", 5 , 3);
	INSERT INTO RATE VALUES(null, 5, 7, "2014/04/24", 5 , 4);
	INSERT INTO RATE VALUES(null, 1, 8, "2014/03/02", 7 , 6);
	INSERT INTO RATE VALUES(null, 1, 9, "2014/11/05", 7 , 7);
	INSERT INTO RATE VALUES(null, 1, 10, "2014/11/15", 7 , 6);
	INSERT INTO RATE VALUES(null, 5, 11, "2014/11/13", 7 , 9);
	INSERT INTO RATE VALUES(null, 5, 12, "2014/11/25", 9 , 3);
	INSERT INTO RATE VALUES(null, 4, 13, "2014/12/01", 9 , 1);
	INSERT INTO RATE VALUES(null, 4, 14, "2014/12/02", 9 , 8);
	INSERT INTO RATE VALUES(null, 5, 15, "2014/12/03", 9 , 8);

	#PICTURE
	INSERT INTO PICTURE VALUES(null, "Image_1", 3 , 1);
	INSERT INTO PICTURE VALUES(null, "Image_2", 3 , 2);
	INSERT INTO PICTURE VALUES(null, "Image_3", 3 , 3);
	INSERT INTO PICTURE VALUES(null, "Image_4", 3 , 4);
	INSERT INTO PICTURE VALUES(null, "Image_5", 5 , 5);
	INSERT INTO PICTURE VALUES(null, "Image_6", 5 , 6);
	INSERT INTO PICTURE VALUES(null, "Image_7", 5 , 7);
	INSERT INTO PICTURE VALUES(null, "Image_8", 5 , 8);
	INSERT INTO PICTURE VALUES(null, "Image_9", 7 , 9);
	INSERT INTO PICTURE VALUES(null, "Image_10", 7 , 1);
	INSERT INTO PICTURE VALUES(null, "Image_11", 7 , 1);
	INSERT INTO PICTURE VALUES(null, "Image_12", 7 , 2);
	INSERT INTO PICTURE VALUES(null, "Image_13", 7 , 3);
	INSERT INTO PICTURE VALUES(null, "Image_14", 9 , 3);
	INSERT INTO PICTURE VALUES(null, "Image_15", 9 , 5);
	INSERT INTO PICTURE VALUES(null, "Image_16", 9 , 5);
	INSERT INTO PICTURE VALUES(null, "Image_17", 9 , 7);
	INSERT INTO PICTURE VALUES(null, "Image_18", 9 , 7);
	INSERT INTO PICTURE VALUES(null, "Image_19", 9 , 9);

	#PROMOTION
	INSERT INTO PROMOTION VALUES(null,"BLACK FRIDAY","2014/11/30",1,1);
	INSERT INTO PROMOTION VALUES(null,"CHRISTMAS SALE","2014/12/25",1,2);
	INSERT INTO PROMOTION VALUES(null,"BLACK FRIDAY","2014/11/30",4,3);
	INSERT INTO PROMOTION VALUES(null,"CHRISTMAS SALE","2014/12/25",4,4);
	INSERT INTO PROMOTION VALUES(null,"NEW YEAR SALE","2015/01/30",4,5);
	INSERT INTO PROMOTION VALUES(null,"BLACK FRIDAY","2014/11/30",6,6);
	INSERT INTO PROMOTION VALUES(null,"CHRISTMAS SALE","2014/12/25",8,7);
	INSERT INTO PROMOTION VALUES(null,"BLACK FRIDAY","2014/11/30",8,8);
	INSERT INTO PROMOTION VALUES(null,"NEW YEAR SALE","2015/01/30",8,9);



	#CHECKIN
	INSERT INTO CHECKIN VALUES(3,1,"2014/11/30");
	INSERT INTO CHECKIN VALUES(3,3,"2014/12/25");
	INSERT INTO CHECKIN VALUES(3,5,"2014/11/30");
	INSERT INTO CHECKIN VALUES(5,7,"2014/12/25");
	INSERT INTO CHECKIN VALUES(5,9,"2015/01/30");
	INSERT INTO CHECKIN VALUES(7,8,"2014/11/30");
	INSERT INTO CHECKIN VALUES(7,6,"2014/12/25");
	INSERT INTO CHECKIN VALUES(7,4,"2014/11/30");
	INSERT INTO CHECKIN VALUES(9,2,"2015/01/30");
	INSERT INTO CHECKIN VALUES(9,6,"2015/01/30");
	INSERT INTO CHECKIN VALUES(9,7,"2015/01/30");
	INSERT INTO CHECKIN VALUES(9,3,"2015/01/30");
COMMIT ;

END; //
DELIMITER ;